
export const SingingEvents = [
  {
    "Event Name": "Solo Singing Eastern",
    "Description": "This theme embodies the deep connection between tradition and innovation in Eastern music and performance. In this eastern solo performance, this theme celebrates artists who carry forward the essence of their cultural origins while infusing it with new life and personal expression. It highlights the harmony between past and present, structure and improvisation, stillness and motion— capturing the soul of Eastern artistry in its purest and most electrifying form. ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aritrita Brahma ",
    "Lead Contact Number": 9354397235,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Solo Singing Western",
    "Description": "Get ready to take the stage and make the audience groove with your beats! This event is all about rhythm, flow, and musicality. Your performance should captivate the audience and make them dance to your rhythm. Whether it's your vocal skills or your ability to engage with the music, the performance should leave a lasting impact.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Jayant Bavouria ",
    "Lead Contact Number": 9541410526,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Duet Singing",
    "Description": "Welcome to the Duet Singing Contest, a celebration of India’s rich and diverse cultural heritage! This event is open to participants from all parts of the nation, and we encourage creativity, passion, and respect for the cultural traditions of India. Whether you’re singing in classical, folk, regional, or contemporary styles, this is an opportunity to showcase your talent while honoring the spirit of Indian culture. ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivam ",
    "Lead Contact Number": 9149454230,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Battle of Bands",
    "Description": "A high-energy Battle of the Bands celebrating the fusion of Indian folk, Bollywood, and indie rock. The stage will come alive with vibrant truck art motifs and a raw, rustic aesthetic, setting the perfect backdrop for electrifying performances. Bands will blend desi rhythms with rock and indie vibes, reimagining classic sounds in bold new ways. Get ready for a night where tradition meets rebellion, and music knows no boundaries",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Gurmeet",
    "Lead Contact Number": 8899433889,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Main Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Solo Instrumental",
    "Description": "Feel the rhythm, embrace the pulse—your music is the heartbeat of this stage Let your instrument speak, pouring out passion, energy, and emotion.Every note you play tells a story—make it powerful, make it unforgettable.This is your moment—let the music flow and make hearts beat with you!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Rajiv Singh ",
    "Lead Contact Number": 7408784223,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Rap Battle",
    "Description": "Step into the spotlight where creativity meets competition! This rap battle is all about sharp lyrics, smooth flows, and unforgettable wordplay. With the crowd hyped and the beats knocking, MCs will go head-to-head, proving who has the wittiest bars and the slickest delivery.Who will rise with the rhythm? Let the battle begin",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aditya Shresth ",
    "Lead Contact Number": 8082525295,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Beatbox",
    "Description": "beatbox experience where tribal rhythms meet futuristic beats! Watch vocal artists fuse earthy drum patterns, nature-inspired sounds, and urban basslines for an electrifying showdown. Featuring beatboxes battles, this is where the rhythms of the past fuel the beats of the future!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aditya Shresth ",
    "Lead Contact Number": 8082525295,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  }
];

export const DancingEvents = [
  {
    "Event Name": "Solo Dance Eastern",
    "Description": "The Solo Eastern Dance Competition is a celebration of tradition, grace, and cultural storytelling. Dancers will captivate the stage with classical, folk, and contemporary Eastern dance forms, showcasing elegance, technique, and deep-rooted heritage. Each performance is a journey through rhythm and expression, honoring the rich traditions of the East. Join us as we witness the beauty of solo artistry, where every step tells a timeless story!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Abhiraj Kanteshwar Roy ",
    "Lead Contact Number": 7298212637,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Solo Dance Western",
    "Description": "A solo western dance is a captivating performance that embodies the spirit of the American West, often blending elements of country, folk, and even modern dance styles. It's a showcase of individual expression, strength, and storytelling, told through movement.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Janvi Duge ",
    "Lead Contact Number": 9699408586,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Duet Freestyle",
    "Description": "'Echoes of Time' is a celebration of dance through the ages, where tradition meets innovation. It blends classical rhythms with contemporary expressions, showcasing the evolution of movement across generations. Each performance is a bridge between past and present, honoring heritage while embracing modern creativity. From folk to freestyle, ballet to hip-hop—this is where history and future dance as one.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Kiran ",
    "Lead Contact Number": 6006624997 ,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Main Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Dance Battle",
    "Description": ": Step onto the stage where movement meets the journey! it is not just a dance battle—it’s a fusion of paths and pulses, a collision of styles and stories. Dancers will channel the energy of different routes—cultural, personal, or urban— while riding the rhythm that drives them forward.",
    "NIT Entry Fee": "NO Fee ",
    "Outside Entry Fee": "100rs/team",
    "Lead Name": "Janvi Duge ",
    "Lead Contact Number": 9699408586,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Choreonight",
    "Description": "Get ready to witness an electrifying dance battle where past meets present! Modern Hits & Retro Rivals is a dynamic group dance competition celebrating the evolution of music and movement. Teams will light up the stage with high-energy performances that blend the groovy charm of retro beats with the bold vibes of modern hits. It’s more than just a competition — it’s a celebration of style, creativity, and rhythm across generations.Whether you're throwing it back to disco and pop classics or bringing the fire with current chart-toppers, each performance should tell a story of contrast, fusion, or transition between eras. Which team will rule the rhythm — the retro rebels or the modern mavens? Let the showdown begin! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs/group",
    "Lead Name": "Akansha Shukla",
    "Lead Contact Number": 9555615498,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Main Stage",
    "Card Image" : "vihang.png"
  }
];

export const competitions = [
  {
    "Event Name": "Heena Art",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "1",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Salsa Dance Workshop",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "1",
    "Venue": "Amphitheatre (near activity centre)",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Clay Art (sculpture making)",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "2",
    "Venue": "Amphitheatre (near activity centre)",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Crochet",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "2",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Fabric Painting",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NULL",
    "Outside Entry Fee": "To Be Decided",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Tattoo Fashion (temporary)",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "2",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  }
];

export const womenCompetitions  = [
  {
    "Event Name": "Stand-Up Comedy",
    "Description": "Serious About Comedy, Giggles loaded Ahead: Stand-Up Comedy Brace yourselves for an unforgettable evening packed with belly laughs, quick wit, and relatable humor! Featuring a lineup of comedic geniuses, this show promises to tickle your funny bone and brighten your day. From hilarious observations about life to side-splitting anecdotes, you'll be taken on a comedic rollercoaster like no other. Whether you're a connoisseur of clever punchlines or a fan of absurd humor, this show guarantees non-stop laughter and entertainment. Grab your friends, and let's turn ordinary moments into extraordinary memories. Are you ready for the fun? Let's get the giggles rolling! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "ABHI BADHERA ",
    "Lead Contact Number": 7732803858,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Mimicry",
    "Description": "SGet ready for a fun-filled evening at our college's Mimicry! Watch your favorite celebrities, characters, and professors come to life as talented performers bring them to the stage with hilarious and spot-on impersonations. An event full of laughter, creativity, and unexpected surprises—don’t miss out on the show!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "ROHIT PRAJAPAT ",
    "Lead Contact Number": 9596271532,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Mushaira",
    "Description": "Mushaira is a gathering of poets where words take center stage and emotions flow effortlessly. It is a celebration of expression, rhythm, and storytelling through poetry. With no fixed theme, poets from all genres are welcome to captivate the audience with their verses. Step forward, let your voice be heard, and create an unforgettable experience through the power of words!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Akanksha Shukla ",
    "Lead Contact Number": 9555615498,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "HiTech",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Monoacting",
    "Description": "Whether it's a heartfelt monologue, an intense dramatic act, or a light-hearted yet meaningful performance, every expression, every gesture, and every word will bring a story to life. Participants will be judged on their ability to captivate the audience, their expressions, dialogue delivery, and stage presence.So, take the stage, let your voice echo through the fest, and leave the audience mesmerized with your performance. Because sometimes, a single voice is all it takes to move a thousand hearts!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Rishabh Shukla ",
    "Lead Contact Number": 8527109671,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Poetry",
    "Description": "Step into a world where words paint landscapes, and emotions echo through time! Wel come to an evening of lyrical beauty and heartfelt expressions at NIT Srinagar’s Poetry Event. Under the enchanting theme of Nature & Nostalgia, poets and enthusiasts will gather to celebrate the magic of poetry—where memories intertwine with the whispers of the wind and verses bloom like wildflowers. Whether you seek solace in nature’s embrace or cherish the bittersweet echoes of the past, this event promises a soulful journey through spoken artistry. Come, immerse yourself in rhythm, rhyme, and raw emotion! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aakash Kumar",
    "Lead Contact Number": 8493866076,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Drama",
    "Description": "Dramatics is the art of storytelling through performance, blending emotion, expression, and stagecraft to bring characters and narratives to life. It encompasses theater, improvisation, and scripted plays, offering a powerful medium for creativity, entertainment, and social commentary. ",
   "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Kumar Sangyanam  ",
    "Lead Contact Number": 9797435297,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Ladishah",
    "Description": "Participants will showcase their talent by performing Ladishah, a traditional Kashmiri satirical storytelling art form. The act should be engaging, humorous, and reflect social or cultural themes in an entertaining manner. Rhythm, wit, and creative expression are encouraged to captivate the audience.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Reeba",
    "Lead Contact Number": 6006993971,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "HiTech",
    "Card Image" : "vihang.png"
  }
];

export const performingEvents = [
  {
    "Event Name": "Haunted House",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NULL",
    "Outside Entry Fee": "To Be Decided",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Civil Attick",
    "Card Image" : "vihang.png"
  }
];

export const womenPerformances = [
  {
    "Event Name": "Mr & Miss Rang-e-Chinar",
    "Description": "Step into the spotlight and embrace your true essence, 'Mr. and Ms. Rang-e-Chinar' is more than just a pageant—it's a celebration of individuality, confidence, and cultural elegance. This competition is designed to bring out the charisma, creativity, and personal expression of every participant.From showcasing impeccable style in couture to exuding unmatched grace and charm, contestants will embark on a journey of self-discovery and artistic presentation. Whether through fashion, performance, or personality, each round will challenge participants to embrace their roots while defining their unique rhythm.This is your chance to shine, to unveil your true self, and to redefine glamour with a touch of authenticity. The stage is yours—own it with Couture and Charisma: The Ultimate Blend! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Deepti Badyal ",
    "Lead Contact Number": 7006863809,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Main Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Face Painting",
    "Description": "'Parallel Realities: The World Through Different Eyes' Imagine how the world looks through the eyes of animals, AI, aliens, or even different emotions. ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivangi Basu ",
    "Lead Contact Number": 9638298285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Wall Painting",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivangi Basu ",
    "Lead Contact Number": 9638298285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Campus",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Stone Painting",
    "Description": "'Cultural Tapestry: Heritage and Traditions of Kashmir' Encourages artists to showcase Kashmir’s rich culture, traditions, folklore, and symbols on stones.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivangi Basu ",
    "Lead Contact Number": 9638298285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Live Photography",
    "Description": "Step into the world of photography and freeze time with your lens! The Live Photography Event is an exciting competition where participants will showcase their ability to capture stunning moments in real-time. This event is all about creativity, perspective, and storytelling through photographs. Let your camera narrate the world as you see it! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Akshay Kumar ",
    "Lead Contact Number": 6005523966,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Campus",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "30 Sec Reel Making",
    "Description": "Unleash your creativity in just 30 seconds! Show off your storytelling, editing, and filming skills by creating a short yet impactful reel that captivates the audience. Whether it’s comedy, drama, action, or pure aesthetics—your vision, your story, your moment to shine! Are you ready to reel it, feel it and win it? ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Gyan",
    "Lead Contact Number": 8051005656,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "No Venue",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Meme Making",
    "Description": "Unleash your creativity and humor at our meme-making event . Join us for an evening of laughter and fun as we create hilarious memes that will make your friends LOL! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "NO Fee",
    "Lead Name": "Yash Pratap Singh ",
    "Lead Contact Number": 9103582285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Short Movie Making",
    "Description": "Step into the world of storytelling where culture meets creativity! 'Lights, Culture, Action!' is a short film competition that invites filmmakers to explore the rhythms of tradition and the roots of identity. From folklore and heritage to music and dance, this event celebrates the vibrant fusion of the past and present through the lens of cinema. Participants will craft compelling short films that showcase cultural narratives, artistic expressions, and the evolution of traditions in today’s world. Whether through powerful storytelling, mesmerizing visuals, or rhythmic beats, each film will bring culture to life on screen. Join us for an unforgettable cinematic journey—where every frame echoes heritage, and every rhythm tells a story! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Zeeshan Nazir ",
    "Lead Contact Number": 914957803,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Open Talent Show For Faculties",
    "Description": "Join us for an exciting evening where faculty members step beyond the lecture halls and into the spotlight! This open talent show is a celebration of the hidden artistic, musical, and performance skills of our educators. From singing and dancing to poetry, comedy, and beyond, watch as professors, lecturers, and staff showcase their incredible talents in a fun, engaging, and unforgettable event. ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Anjali Kacher ",
    "Lead Contact Number": 8400357741,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Tea Cronicals",
    "Description": "Teatime Chronicles is a simple and fun storytelling event where students share their stories, and we serve them tea. It is a place to talk, listen, and connect over a warm cup of tea",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Disha ",
    "Lead Contact Number": 6005177134,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Amphitheatre (near activity centre)",
    "Card Image" : "vihang.png"
  }
];

export const gamezone = [
  {
    "Event Name": "",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NULL",
    "Outside Entry Fee": "To Be Decided",
    "Lead Name": "",
    "Lead Contact Number": "",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "",
    "Card Image" : "vihang.png"
  }
];

export const talks = [
  {
    "Event Name": "Microcontrollers, \nHands on practice \nwith Arduino UNO",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Mr. Kaif Nabi Wani & Mr. Murtaza",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "1:00 pm",
    "Day": 1,
    "Venue": "L-11",
    "isWorkshop": true,
    "Card Image" : "Adrino_Techtalks.png"
  },
  {
    "Event Name": "Introduction To Drones",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Mr. Abid Fayaz ",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 pm",
    "End Time": "1:00 pm",
    "Day": 1,
    "Venue": "L-10",
    "isWorkshop": true,
    "Card Image": "intro-to-drones.png",
  },
  {
    "Event Name": "Solid Works",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Roshan Kumar",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "1:30 pm",
    "End Time": "5:00 pm",
    "Day": 1,
    "Venue": "L-8",
    "isWorkshop": true,
    "Card Image": "Solid Works.png",
  },
  {
    "Event Name": "ML",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "1:30 pm",
    "End Time": "5:00 pm",
    "Day": 1,
    "Venue": "L-9",
    "isWorkshop": true,
    "Card Image": "ML.png",
  },
  {
    "Event Name": "Python",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "1:30 pm",
    "Day": 1,
    "Venue": "L-12",
    "isWorkshop": true,
    "Card Image": "Python.png",
  },
  {
    "Event Name": "Robotics",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "1:30 pm",
    "Day": 2,
    "Venue": "L-10",
    "isWorkshop": true,
    "Card Image": "Robotics.png",
  },
  {
    "Event Name": "AI",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "1:30 pm",
    "Day": 2,
    "Venue": "L-11",
    "isWorkshop": true,
    "Card Image": "AI.png",
  },
  {
    "Event Name": "App Development",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "1:30 pm",
    "Day": 2,
    "Venue": "L-12",
    "isWorkshop": true,
    "Card Image": "App Development.png",
  },
  {
    "Event Name": "Web Development",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "1:30 pm",
    "Day": 2,
    "Venue": "L-13",
    "isWorkshop": true,
    "Card Image": "Web Development.png",
  },
  {
    "Event Name": "Internet Of Things (IoT)",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "1:30 pm",
    "End Time": "5:00 pm",
    "Day": 2,
    "Venue": "L-6",
    "isWorkshop": true,
    "Card Image": "IOT.png",
  },
 /*  {
    "Event Name": "3D modelling",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "1:30 pm",
    "End Time": "5:00 pm",
    "Day": 2,
    "Venue": "LH3",
    "isWorkshop": true,
    "Card Image": "3D Modelling.png",
  },
  {
    "Event Name": "CAD",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00",
    "End Time": "13:00",
    "Day": 1,
    "Venue": "LH3",
    "isWorkshop": true,
    "Card Image": "CAD.png",
  },
  {
    "Event Name": "CLC(Computerised Numerical Control) ",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00",
    "End Time": "13:00",
    "Day": 1,
    "Venue": "LH3",
    "isWorkshop": true,
    "Card Image": "CLC(Computerised.png",
  },
  {
    "Event Name": "Circuit Designing",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00",
    "End Time": "13:00",
    "Day": 1,
    "Venue": "LH3",
    "isWorkshop": true,
    "Card Image": "Circuit Designing.png",
  },
  {
    "Event Name": "Electric Vehicles",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00",
    "End Time": "13:00",
    "Day": 1,
    "Venue": "LH3",
    "isWorkshop": true,
    "Card Image": "Electric Vehicle.png",
  },
  {
    "Event Name": "LaTeX (Document Preparation System)",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "MSME",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00",
    "End Time": "13:00",
    "Day": 1,
    "Venue": "LH3",
    "isWorkshop": true,
    "Card Image": "LateX.png",
  }, */
  {
    "Event Name": "Thermocalc",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "1:30 pm",
    "End Time": "5:00 pm",
    "Day": 2,
    "Venue": "L-7",
    "isWorkshop": true,
    "Card Image": "thermo-workshop.png",
  },
  {
    "Event Name": "Aspen Hysys",
    "Description": "Tech Workshops at Techvaganza 2024 offer hands-on learning experiences across a wide range of cutting-edge technologies and practical tools. Whether you're eager to explore Drones, SolidWorks, or Microcontrollers with Arduino UNO, or dive into specialized topics like Vernacular Building Styles for earthquake-prone areas, these workshops will provide the skills and knowledge to thrive in today's tech-driven world.Participants will have the opportunity to learn about the latest advancements in Machine Learning, Python, Robotics, AI, App Development, and Web Development. In addition, the MSME-led sessions will focus on key technologies like IoT, 3D Modelling, CAD, CNC, Circuit Designing, Electric Vehicles, and even advanced tools like LaTeX for document preparation. For those interested in computational tools, workshops on Thermocalc and Aspen Hysys will also be available. These workshops are designed to provide practical, hands-on experience, making them ideal for students and professionals looking to expand their skillset in the tech space.",
    "Description about Instructor / Speaker": "Robonox",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "1:30 pm",
    "End Time": "5:00 pm",
    "Day": 2,
    "Venue": "L-8",
    "isWorkshop": true,
    "Card Image": "aspen-hysys.png",
  },
  {
    "Event Name":
      "Vernacular Building styles",
    "Description":
      "This workshop delves into the traditional architecture of Kashmir focusing on the principles of vernacular building styles in face of earthquakes. It will establish a detailed study of key techniques such as Dhajji Dewari and Taq construction which have demonstrated earthquake resilience and analysis of successful preservation and adaptation of vernacular buildings in Kashmir.",
    "Description about Instructor / Speaker": "Dr. Rakesh Chandra (KU)",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Tanisha Khan",
    "Lead Contact Number": 9149844814,
    "Start Time": "10:00 am",
    "End Time": "1:00 PM",
    "Day": 1,
    "Venue": "L-13",
    "isWorkshop": true,
    "Card Image":
      "Vernacular Building styles and Earthquake Prone Areas with Special reference to Kashmir workshop.png",
  },
  {
    "Event Name": "Empowering Financial Literacy: Transforming Futures Through EdTech ",
    "Description": "In this workshop, we will explore how technology is being used to revolutionize financial literacy. Participants will learn about various EdTech platforms and tools that simplify complex financial concepts, making them accessible to all. By the end of the session, you will understand how to use these tools to make better financial decisions and how EdTech is creating a more financially literate and empowered society.",
    "Description about Instructor / Speaker": "Mr. Punit G. is an inspiring professional with a diverse career across multiple industries. He pursued veterinary medicine at Bombay Veterinary College before moving into management with a Post Graduate Program (PGP) from IIM Ahmedabad. He is the founder of Arth Nirmiti, co-founder of Social-Noise, and has launched and scaled businesses globally, including in the USA, Japan, and Europe. With leadership roles spanning FMCG, digital marketing, and hospitality, Punit’s journey is a testament to determination and adaptability in navigating complex challenges and achieving excellence.",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-3",
    "isWorkshop": false,
    "Card Image": "Empowering Financial Literacy.png",
  },
  {
    "Event Name": "AI & Animal Husbandry ",
    "Description": "This workshop will focus on the integration of Artificial Intelligence in animal husbandry. Participants will gain insights into how AI can optimize breeding, health monitoring, and milk production, improving both the welfare of animals and the productivity of farms. Case studies and real-life applications will be discussed to showcase the future of AI in enhancing the efficiency and sustainability of animal farming",
    "Description about Instructor / Speaker": "Dr Ambreen Hamdani (SKAUST) ",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 2,
    "Venue": "L-3",
    "isWorkshop": false,
    "Card Image": "AI & Animal Husbandry.png",
  },
  {
    "Event Name": "Electric Vehicles: Driving Sustainability",
    "Description": "Join us in exploring the latest trends and innovations in Electric Vehicles (EVs). This workshop will provide an in-depth look into the sustainable benefits of EVs, the technology behind them, and the challenges they face. You will leave with a comprehensive understanding of the role EVs play in reducing carbon footprints and how this technology is shaping the future of transportation.",
    "Description about Instructor / Speaker": "Dr Salman Ahmad (IUST)",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "11:30 am",
    "Day": 1,
    "Venue": "L-1",
    "isWorkshop": false,
    "Card Image": "The Future of Electric Vehicles Driving.png",
  },
  {
    "Event Name": "Renewable Energy: Path to a Sustainable Future",
    "Description": "This workshop delves into the importance of renewable energy in combating climate change. We will explore various renewable energy sources such as solar, wind, and hydro, and discuss their potential to replace fossil fuels. The session will include interactive case studies on how renewable energy can be implemented on both small and large scales to create a sustainable future.",
    "Description about Instructor / Speaker": "Dr Sharique Anees (IUST)",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "11:30 am",
    "Day": 1,
    "Venue": "L-2",
    "isWorkshop": false,
    "Card Image": "Renewable Energy Pathway to a.png",
  },
  {
    "Event Name": "Talk on AI",
    "Description": "This workshop is an introduction to Artificial Intelligence and its applications across different industries. Participants will learn about the core concepts of AI, machine learning, and deep learning, with hands-on examples to see how AI is transforming fields such as healthcare, finance, and robotics. By the end of the workshop, attendees will have a better grasp of AI's potential and how it can be utilized in real-world scenarios.",
    "Description about Instructor / Speaker": "Dr. Rukhsan-ul-haq",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-1",
    "isWorkshop": false,
    "Card Image": "AI.png",
  },
  {
    "Event Name": "BIO-GENESIS",
    "Description": "In this workshop, participants will explore cutting-edge bioengineering techniques that leverage bacterial synergy to enhance soil health and sustainability. The focus will be on how microorganisms interact with soil components to promote nutrient availability, improve soil structure, and support plant growth. Through hands-on activities, attendees will learn practical applications of bioengineering in agriculture, including the development of sustainable farming practices that reduce dependency on chemical fertilizers and enhance long-term soil fertility.",
    "Description about Instructor / Speaker": "Dr. Kh Mohammad Najmu Saquib Wani (SKUAST)",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "99",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 2,
    "Venue": "L-5",
    "isWorkshop": false,
    "Card Image": "biogenesis.png",
  },
  {
    "Event Name": "Electrospun Nanofibers: New Frontiers in Targeted Drug Delivery",
    "Description": "This technical workshop will introduce participants to the world of electrospun nanofibers and their role in drug delivery systems. We will explore how these materials allow for precise, controlled drug release, enhancing the efficacy of treatments. Through demonstrations and case studies, attendees will see how nanotechnology is revolutionizing healthcare and medicine.",
    "Description about Instructor / Speaker": "Dr Nisar Ahmad Khan (KU)",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 2,
    "Venue": "L-2",
    "isWorkshop": false,
    "Card Image": "Electrospun nanofibers - Opening new.png",
  },
  {
    "Event Name": "Graph Applications Across Diverse Domains",
    "Description": "In this workshop, participants will learn how knowledge graphs are used to model relationships and data across various domains like healthcare, finance, and education. Attendees will engage in hands-on activities to understand how knowledge graphs can simplify complex systems, improve decision-making, and drive innovation across industries. Practical applications and case studies will be discussed to solidify understanding",
    "Description about Instructor / Speaker": "Dr Veningston K ",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-2",
    "isWorkshop": false,
    "Card Image": "Knowledge Graph Applications.png",
  },
  {
    "Event Name": "Black Holes",
    "Description": "This workshop is an exciting journey into the mysteries of black holes. We will delve into the fundamental science of black holes, discussing their formation, behavior, and the latest discoveries in astrophysics. Through interactive discussions, participants will gain a deep understanding of these enigmatic objects and their importance in understanding the universe.",
    "Description about Instructor / Speaker": "Professor Prince Ahmad Ganai",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "11:30 pm",
    "Day": 2,
    "Venue": "L-1",
    "isWorkshop": false,
    "Card Image": "Black Holes.png",
  },
  {
    "Event Name": "Multifunctional Grid Connected PV System ",
    "Description": "This workshop will cover the design, implementation, and benefits of multifunctional grid-connected photovoltaic (PV) systems. Participants will explore how PV systems can provide not only clean energy but also enhance grid stability. Practical examples and real-world case studies will be used to show how solar energy systems are integrated into modern electrical grids",
    "Description about Instructor / Speaker": "Dr Ikhlaq Hussain",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "11:30 pm",
    "Day": 2,
    "Venue": "L-2",
    "isWorkshop": false,
    "Card Image": "Multifunctional Grid.png",
  },
  {
    "Event Name": "A novel class of material",
    "Description": "Join this workshop to discover a new class of materials that are breaking new ground in science and technology. We will cover their unique properties and potential applications in industries such as electronics, renewable energy, and biomedicine. Participants will engage in interactive sessions that highlight the role these materials will play in future technological advancements.",
    "Description about Instructor / Speaker": "Dr. Harkirat Singh",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "10:00 am",
    "End Time": "11:30 pm",
    "Day": 2,
    "Venue": "L-3",
    "isWorkshop": false,
    "Card Image": "A novel class of material.png",
  },
  // {
  //   "Event Name": "Applications of Hydrogen Storage Materials ",
  //   "Description": "In this workshop, participants will explore the emerging field of hydrogen storage materials, a key component of the future energy landscape. We will discuss how these materials enable efficient storage of hydrogen, a clean energy source, and the various industrial applications that are being developed. Through case studies and technical discussions, you will gain insights into how hydrogen storage can support global energy sustainability efforts.",
  //   "Description about Instructor / Speaker": "Dr. Anshul Gupta ",
  //   "Prizes": "",
  //   "NIT Entry Fee": "",
  //   "Outside Entry Fee": "49",
  //   "Lead Name": "Mubashir Malik",
  //   "Lead Contact Number": 7780916523,
  //   "Judging Criteria": "",
  //   "Start Time": "2:00 pm",
  //   "End Time": "3:30 pm",
  //   "Day": 1,
  //   "Venue": "L-1",
  // "isWorkshop": false,   
  // "Card Image": "Applications of Hydrogen.png",
  // },
  {
    "Event Name": "Tech role in Heritage Preservation",
    "Description": "This workshop focuses on how technology is being used to preserve cultural heritage. Participants will learn about the use of digital tools such as 3D scanning, augmented reality, and data archiving to protect and restore heritage sites. Through interactive demonstrations, attendees will gain an understanding of how tech innovations are helping safeguard our history for future generations",
    "Description about Instructor / Speaker": "Muneer Ahmad Dar ",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-4",
    "isWorkshop": false,
    "Card Image": "Tech role in Heritage Preservation.png",
  },
  {
    "Event Name": "Career Counselling ",
    "Description": "This workshop will provide participants with essential strategies for career development in today’s dynamic job market. Through personalized guidance and interactive activities, attendees will learn how to assess their strengths, set career goals, and navigate different industries. The workshop will also include insights on how to adapt to the fast-changing demands of the tech industry",
    "Description about Instructor / Speaker": "Salman Shahid ",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-5",
    "isWorkshop": false,
    "Card Image": "Career Counselling.png",
  },
  {
    "Event Name": "Mental Health ",
    "Description": "Expert Talks at Techvaganza 2024 will present an exciting lineup of sessions, offering valuable insights into cutting-edge technologies, scientific advancements, and societal challenges. Explore topics like Electric Vehicles, Renewable Energy Systems, and the latest in Artificial Intelligence and Knowledge Graph Applications, shedding light on their impact across diverse domains. Additionally, learn about the role of technology in preserving cultural legacies with Tech's Role in Heritage Preservation, or delve into personal growth with sessions on Career Counselling, Mental Health, and Content Creation. Discover innovative approaches to Financial Literacy through EdTech and gain exposure to breakthroughs in Multifunctional Grid-Connected PV Systems, Hydrogen Storage Materials, and a Novel Class of Materials that have promising industrial applications. Furthermore, the session on the Art of Persuasion: Writing Skills for the Tech World will provide essential guidance on crafting impactful documents, crucial for success in the tech industry. With a talk on advanced Chemistry also in the mix, this event promises to cater to a wide spectrum of interests, offering attendees ample opportunity to learn and engage with experts.",
    "Description about Instructor / Speaker": "Feroz Ahmad Malla",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-6",
    "isWorkshop": false,
    "Card Image": "Mental Health.png",
  },
  {
    "Event Name": "Content Creation",
    "Description": "In this workshop, participants will dive into the world of content creation, learning how to produce engaging digital content across platforms like YouTube, social media, and blogs. Topics will include storytelling techniques, video production, and effective use of SEO to reach broader audiences. Attendees will leave with practical tips to create content that stands out in today’s digital age.",
    "Description about Instructor / Speaker": "Nufeel Mir",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 1,
    "Venue": "L-7",
    "isWorkshop": false,
    "Card Image": "Content Creation.png",
  },
  {
    "Event Name": "Art of Persuasion: Writing Skills for the Tech World",
    "Description": "This workshop will teach participants the art of persuasive writing, a crucial skill in the tech industry. We will explore techniques to craft compelling emails, proposals, and documentation that can effectively communicate technical concepts to diverse audiences. Through practical exercises, attendees will enhance their ability to write with clarity and impact in a tech-driven environment.",
    "Description about Instructor / Speaker": "Faheem ul Islam",
    "Prizes": "",
    "NIT Entry Fee": "",
    "Outside Entry Fee": "49",
    "Lead Name": "Mubashir Malik",
    "Lead Contact Number": 7780916523,
    "Judging Criteria": "",
    "Start Time": "2:00 pm",
    "End Time": "3:30 pm",
    "Day": 2,
    "Venue": "L-4",
    "isWorkshop": false,
    "Card Image": "Art of Persuasion Writing.png",
  }
];

export const womenTalks = [
  {
    "Event Name": "To be a girl leader: Leadership Workshop",
    "Description": "Session Overview By The Guest Speaker :;    Brief speech on the concept of leadership, its significance, and the objectives of the workshop highlighting the importance of qualities such as decision-making, teamwork, and creative problem-solving will be given by the speaker.\n\n;2.     \"What If\" Scenario Game  ;       Rules and Guidelines for the Game :; \n        (1) Volunteers will be selected from the audiences, who will be grouped in teams and they will be presented with different ;\"What If\" leadership scenarios such as: \n ;          ->\"What if a woman in your team is overqualified for their role and the rest of the team members are men?\" \n  ;         ->\"What if you were in charge of organizing a college-wide female talent  show?\" \n   ;     (2) The teams will brainstorm the situation for 3-5 minutes and come up with an answer that will be presented by the leader. This will emphasize leadership qualities like adaptability, decision-making, and managing diverse talents. \n\n     ;    Awards:\n        ; Attendees with the most innovative and practical solutions will be recognized with Prizes, fostering competitive yet constructive engagement. \n \n;3.      Survival Scenario Game  . \n;      Rules and Guidelines for the Game :  \n;        A survival scenario will be presented (e.g., stranded on a desert island after a plane crash).and a list of items such as matches, knives, water, medicines, etc. will be provided to the participants.  The attendees(individually or in teams) will be asked to prioritize these items based on the given scenario. ; For  e.g:  If the group includes elderly people, medicines may be prioritized. \n; For instance:  You are a woman whose village was recently hit by a tsunami . The villagers , including old people and children are in a state of fear . You decided to step up as              a leader and  build various shelter homes , look for food supplies , medicines , emergency medical equipment , etc . Despite the criticism and demotivation you received from the villagers because a \"woman \" decided to step up as the leader , how will you face the scenario and look for better lives ahead for the people in your village ? \n ;  After 5-7 minutes of brainstorming, participants will explain the rationale behind their choices and how it reflects leadership in crisis situations. This will induce stress handling and resource management capabilities amongst the attendees.\n  ;    \n4.       Conclusion and Q&A  \nA Q&A session will open the floor for questions, allowing attendees to clarify doubts, share their experiences, and seek advice from the guest speaker on leadership challenges they may face. This interactive discussion will foster a deeper understanding of effective leadership and encourage participants to apply these insights in their own journeys.",
    "Description about Instructor / Speaker": "Dr. Fouzia Jan , Assistant Professor , Department of HSS&M",
    "Outside Entry Fee": "49: Common fee for accessing all women in tech events",
    "Lead Name": "Hurmat Khalid",
    "Lead Contact Number": "8082251200",
    "Start Time": "10:00 a.m",
    "End Time": "12:00 noon",
    "Day": 1,
    "isWomen": true,
    "isWorkshop": true,
    "Venue": "Venue- L-5",
    "Card Image": "Women in techbreaking boundaries.png"
  },
  {
    "Event Name": "Skill building workshop",
    "Description": "Attendees will engage in hands-on activities covering key topics such as coding, data analysis, software development, and more. Through interactive sessions and collaborative projects, youll gain practical experience and apply your skills in real-world scenarios.\nWhether youre a beginner or looking to advance your existing knowledge, this workshop caters to all skill levels. Join us to connect with fellow tech enthusiasts, expand your network, and take your technical skills to the next level. Dont miss this opportunity to invest in your future.",
    "Description about Instructor / Speaker": "",
    "Outside Entry Fee": "49: Common fee for accessing all women in tech events",
    "Lead Name": "Hurmat Khalid",
    "Lead Contact Number": "8082251200",
    "Start Time": "4:00 p.m",
    "End Time": "7:00 p.m.",
    "Day": 2,
    "isWomen": true,
    "isWorkshop": true,
    "Venue": "L5",
    "Card Image": "Tech ForwardEmpowering Women in STEM.png"
  },
  {
    "Event Name": "Expert talk 1",
    "Description": "TOPIC: Breaking Barriers: Inspiring the Next Generation of Women in STEM, Resilience and Innovation: Inspiring Young Women to Lead in STEM.",
    "Description about Instructor / Speaker": "Dr. Rishi Richa",
    "Outside Entry Fee": "49: Common fee for accessing all women in tech events",
    "Lead Name": "Hurmat Khalid",
    "Lead Contact Number": "8082251200",
    "Start Time": "12:30am",
    "End Time": "2:00am",
    "Day": 1,
    "isWomen": true,
    "isWorkshop": false,
    "Venue": "L5",
    "Card Image": "HerTech TalksInsights from Women Innovators.png"
  },
  {
    "Event Name": "Expert talk 2",
    "Description": "TOPIC: Security and privacy issues in 5g- URLLC network slice",
    "Description about Instructor / Speaker": "Syed Rameem Zahra",
    "Outside Entry Fee": "49: Common fee for accessing all women in tech events",
    "Lead Name": "Hurmat Khalid",
    "Lead Contact Number": "8082251200",
    "Start Time": "2:00am",
    "End Time": "3:30pm",
    "Day": 2,
    "isWomen": true,
    "isWorkshop": false,
    "Venue": "L12",
    "Card Image": "HerTech TalksInsights from Women Innovators.png"
  }
]


// For day 1 events
const day1Competitions = competitions
  .map((event, index) => ({
    ...event,
    category: "competitions",
    url: `competitions/${index}`,
  }))
  .filter((event) => event.Day === 1 || event.Day === "");

const day1Talks = talks
  .map((event, index) => ({
    ...event,
    category: "talks",
    url: `talks-and-workshops/${index}`,
  }))
  .filter((event) => event.Day === 1 || event.Day === "");

const day1Gamezone = gamezone
  .map((event, index) => ({
    ...event,
    category: "gamezone",
    url: `gaming-zone/${index}`,
  }))
  .filter((event) => event.Day === 1 || event.Day === "");

const day1Performances = performingEvents
    .map((event, index) => ({
      ...event,
      category: "performances",
      url: `performances/${index}`,
    }))
    .filter((event) => event.Day === 1 || event.Day === "");

const day1womenCompetitions = womenCompetitions
  .map((event, index) => ({
    ...event,
    category: "competitions",
    url: `competitions/${index}`,
  }))
  .filter((event) => event.Day === 1 || event.Day === "");

const day1womenTalks = womenTalks
  .map((event, index) => ({
    ...event,
    category: "talks",
    url: `talks-and-workshops/${index}`,
  }))
  .filter((event) => event.Day === 1 || event.Day === "");

const day1womenPerformances = womenPerformances
    .map((event, index) => ({
      ...event,
      category: "performances",
      url: `performances/${index}`,
    }))
    .filter((event) => event.Day === 1 || event.Day === "");

// For day 2 events
const day2Competitions = competitions
  .map((event, index) => ({
    ...event,
    category: "competitions",
    url: `competitions/${index}`,
  }))
  .filter((event) => event.Day === 2 || event.Day === "");

const day2Talks = talks
  .map((event, index) => ({
    ...event,
    category: "talks",
    url: `talks-and-workshops/${index}`,
  }))
  .filter((event) => event.Day === 2 || event.Day === "");

const day2Gamezone = gamezone
  .map((event, index) => ({
    ...event,
    category: "gamezone",
    url: `gaming-zone/${index}`,
  }))
  .filter((event) => event.Day === 2 || event.Day === "");

const day2Performances = performingEvents
    .map((event, index) => ({
      ...event,
      category: "performances",
      url: `performances/${index}`,
    }))
    .filter((event) => event.Day === 2 || event.Day === "");
  
    const day2womenCompetitions = womenCompetitions
    .map((event, index) => ({
      ...event,
      category: "competitions",
      url: `competitions/${index}`,
    }))
    .filter((event) => event.Day === 2 || event.Day === "");
  
  const day2womenTalks = womenTalks
    .map((event, index) => ({
      ...event,
      category: "talks",
      url: `talks-and-workshops/${index}`,
    }))
    .filter((event) => event.Day === 2 || event.Day === "");
  
  const day2womenPerformances = womenPerformances
      .map((event, index) => ({
        ...event,
        category: "performances",
        url: `performances/${index}`,
      }))
      .filter((event) => event.Day === 2 || event.Day === "");
  

// Combine all day 1 events
export const day1Events = [...day1Competitions, ...day1Talks, ...day1Gamezone, ...day1Performances, ...day1womenCompetitions, ...day1womenTalks, ...day1womenPerformances];

// Combine all day 2 events
export const day2Events = [...day2Competitions, ...day2Talks, ...day2Gamezone, ...day2Performances, ...day2womenCompetitions, ...day2womenTalks, ...day2womenPerformances];


